[package]
name          = "kademlia_routing_table"
readme        = "README.md"
license       = "GPL-3.0"
version       = "0.0.1"
authors       = ["MaidSafe Developers <dev@maidsafe.net>"]
homepage      = "http://maidsafe.net"
repository    = "https://github.com/maidsafe/kademlia_routing_table"
description   = "Kademlia Routing Table implementation"
documentation = "http://maidsafe.net/kademlia_routing_table/latest"

[dependencies]
# ---- Non-MaidSafe -----
cbor = "~0.3.16"
log = "~0.3.3"
rand = "~0.3.12"
rustc-serialize = "~0.3.16"
sodiumoxide = "~0.0.9"
time = "~0.1.34"

# ---- MaidSafe ------
crust = "~0.5.1"

[dev-dependencies]
bit-vec = "~0.4.2"
